<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>conf</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\[.*\])(\((!)?.*?\))?</string>
	<key>foldingStopMarker</key>
	<string>?=\[</string>
	<key>name</key>
	<string>Asterisk config</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\[(macro-)?.*\])(?:\((!)?\s*,?(?:\s*(\w+)\s*,?)*\))?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.modifier</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.modifier</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>entity.other-inherited-class</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?=\[)</string>
			<key>name</key>
			<string>meta.section</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(exten)\s*(=&gt;)\s*(a|h|i|o|s|t|T|e|failed|fax|talk|receiver|(?:_[0-9XZN!\.]+)),(\d+|n)(\(.*?\))?,</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>4</key>
						<dict>
							<key>name</key>
							<string>support.constant</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>support.class</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>meta.extension</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>begin</key>
							<string>(NoOp|Answer|Dial|Hangup|Busy|MixMonitor|GotoIf|Goto|Set|Macro|Queue)\(?</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>support.function</string>
								</dict>
							</dict>
							<key>end</key>
							<string>\)?\s*$</string>
							<key>name</key>
							<string>meta.internal.function</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>\$\{.*\}</string>
									<key>name</key>
									<string>support.variable</string>
								</dict>
								<dict>
									<key>match</key>
									<string>\?\w+:\w+</string>
									<key>name</key>
									<string>support.other</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*([a-zA-Z_-]+)\s*(=)(?!&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>variable.parameter</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>meta.expression</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#path_value</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#ip_netmask_value</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#net_address_value</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#boolean_value</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>^\s*(include|[a-zA-Z_-]+)\s*(=&gt;)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.control</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>keyword.operator</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>name</key>
					<string>meta.command</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#path_value</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#ip_netmask_value</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#net_address_value</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#boolean_value</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>boolean_value</key>
		<dict>
			<key>match</key>
			<string>\b(true|false|yes|no|all)\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>1</key>
			<dict>
				<key>name</key>
				<string>punctuation.definition.comment</string>
			</dict>
			<key>match</key>
			<string>(;).*$\n?</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<key>ip_netmask_value</key>
		<dict>
			<key>match</key>
			<string>\b((?:\d{1,3}\.){3}\d{1,3})(?:/((?:\d{1,3}\.){3}\d{1,3}))?\b</string>
			<key>name</key>
			<string>constant.other</string>
		</dict>
		<key>net_address_value</key>
		<dict>
			<key>match</key>
			<string>(\w+://)?((\w+:)?\w+@)?([\w-]+\.)+[a-zA-Z-]+(:\d+)?</string>
			<key>name</key>
			<string>constant.other</string>
		</dict>
		<key>path_value</key>
		<dict>
			<key>match</key>
			<string>(/[\w-]+)+(\.[\w-]+)?</string>
			<key>name</key>
			<string>constant.other</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.asterisk.config</string>
	<key>uuid</key>
	<string>01514276-8d8f-49e6-a8f3-08642d7f8b33</string>
</dict>
</plist>
